In [1]:
import torch

In [2]:
x = torch.Tensor([8.1, 0.2, 3.4, 2.2, 5.5])
print(x)

tensor([8.1000, 0.2000, 3.4000, 2.2000, 5.5000])


In [4]:
_, x_idx = x.sort(dim=-1, descending=True)
print(x_idx)

tensor([0, 4, 2, 3, 1])


In [5]:
_, x_rank = x_idx.sort(dim=-1)
print(x_rank)

tensor([0, 4, 2, 3, 1])


In [ ]:
# x_rankはxの値(損失)が降順ソートに基づいて上から何番目かを知らせる

In [76]:
# GT-Box:2, Def-Box:3
overlaps = torch.Tensor([[.1,.2,.3,.0,.7], [.4,.0,.2,.6,.1]])
print(overlaps)

tensor([[0.1000, 0.2000, 0.3000, 0.0000, 0.7000],
        [0.4000, 0.0000, 0.2000, 0.6000, 0.1000]])


In [77]:
best_dbox_overlap, best_dbox_idx = overlaps.max(dim=1, keepdim=True)
print(best_dbox_overlap)
print(best_dbox_idx)

tensor([[0.7000],
        [0.6000]])
tensor([[4],
        [3]])


In [78]:
best_gtbox_overlap, best_gtbox_idx = overlaps.max(dim=0, keepdim=True)
print(best_gtbox_overlap)
print(best_gtbox_idx)

tensor([[0.4000, 0.2000, 0.3000, 0.6000, 0.7000]])
tensor([[1, 0, 0, 1, 0]])


In [79]:
best_gtbox_idx.squeeze(0)

tensor([1, 0, 0, 1, 0])

In [80]:
best_dbox_idx.squeeze(1)

tensor([4, 3])

In [81]:
print(best_gtbox_idx)
print(best_dbox_idx)

tensor([[1, 0, 0, 1, 0]])
tensor([[4],
        [3]])


In [82]:
a = best_gtbox_overlap.squeeze(0)
print(a)
b = best_dbox_idx.squeeze(1)
print(b)
c = a.index_fill_(dim=0, index=b, value=2)
print(c)

tensor([0.4000, 0.2000, 0.3000, 0.6000, 0.7000])
tensor([4, 3])
tensor([0.4000, 0.2000, 0.3000, 2.0000, 2.0000])


In [83]:
best_gtbox_overlap.squeeze_(0)
best_dbox_idx.squeeze_(1)
best_gtbox_overlap.index_fill_(dim=0, index=best_dbox_idx, value=2)
print(best_dbox_idx.size(0))
best_gtbox_idx.squeeze_(0)
print(best_gtbox_idx)
for j in range(best_dbox_idx.size(0)):
    best_gtbox_idx[best_dbox_idx[j]] = j
print(best_gtbox_idx)

2
tensor([1, 0, 0, 1, 0])
tensor([1, 0, 0, 1, 0])
